### ISSUE TITLE
[Release v1.6]: checklist

### ISSUE THREAD

**Issue by psschwei** [knative/release#141]
## Week of June 13
- [x] T-minus 30 days - Prior release leads have been removed from rotation
- [x] T-minus 30 days - New release leads have been added for the new rotation
- [x] T-minus 30 days - A new Slack channel for the release has been created

## Week of June 27
- [x] T-minus 14 days - The releasability defaults have been updated
- [x] T-minus 14 days - The releasability defaults update have been propagated thru all applicable `knative.dev` repos
- [x] T-minus 14 days - An announcement has been made in the **#general** Slack channel that `pkg` will be released in a week

## Week of July 4
- [x] T-minus 7 days - A fresh HackMD release notes document has been pinned to the **#*release-xdotx** Slack channel
- [x] T-minus 7 days - A draft for the announcement blog post has been started
- [x] T-minus 7 days - An announcement has been made in the **#general** Slack channel that the cut of `pkg` is immminent
- [x] T-minus 7 days - The nightly release build status has been verified for each of the core knative.dev repos
- [x] knative.dev/hack
- [x] knative.dev/pkg
- [x] knative.dev/networking
- [x] knative.dev/caching
- [x] knative.dev/reconciler-test
- [x] knative.dev/control-protocol

## Week of July 11
- [x] T-minus 1 day - Obtained ACK from each WG leads that the release is imminent and is green-lighted
- [x] T-minus 1 day - A re-check of the nightly release build status has been done for each of the core knative.dev repos
- [x] knative.dev/serving
- [x] knative.dev/net-certmanager
- [x] knative.dev/net-contour
- [x] knative.dev/net-http01
- [x] knative.dev/net-istio
- [x] knative.dev/net-kourier
- [x] knative.dev/net-gateway-api
- [x] knative.dev/eventing
- [x] knative.dev/sample-controller
- [x] knative.dev/eventing-ceph
- [x] knative.dev/eventing-kogito
- [x] knative.dev/eventing-rabbitmq
- [x] knative.dev/sample-source
- [x] knative.dev/client
- [x] knative.dev/eventing-kafka
- [x] knative.dev/eventing-redis
- [x] knative.dev/eventing-github
- [x] knative.dev/eventing-gitlab
- [x] knative.dev/eventing-kafka-broker
- [x] knative.dev/eventing-autoscaler-keda
- [x] knative.dev/kn-plugin-admin
- [x] knative.dev/kn-plugin-event
- [x] knative.dev/kn-plugin-source-kafka
- [x] knative.dev/kn-plugin-source-kamelet
- [x] knative.dev/kn-plugin-quickstart
- [x] Post release - Homebrew tap has been updated
- [x] Post release - The client plugin's Homebrew repo has been updated
- [x] Post release - Release schedule has been updated
- [x] Post release - An announcement was made in the **#general** and **#operation** Slack channels that the new Knative release is out
- [x] Post release - A blog post announcing the release has been published

**Comment by psschwei** [comment]
https://knative.dev/blog/releases/announcing-knative-v1-6-release/

Thanks @evankanderson , looks like we'll be doing this again in November (unless the release cycle extension goes through before then...)
