### ISSUE TITLE
[Release v1.7]: checklist

### ISSUE THREAD

**Issue by dprotaso** [knative/release#154]
### Please change the title to include the current release version.

- [ ] T-minus 30 days - Prior release leads have been removed from rotation
- [ ] T-minus 30 days - New release leads have been added for the new rotation
- [ ] T-minus 30 days - A new Slack channel for the release has been created
- [ ] T-minus 30 days - Knobots update-deps job has been bumped to new release version
- [ ] T-minus 14 days - The releasability defaults have been updated
- [ ] T-minus 14 days - The releasability defaults update have been propagated thru all applicable `knative.dev` repos
- [ ] T-minus 14 days - An announcement has been made in the **#general** Slack channel that `pkg` will be released in a week
- [ ] T-minus 7 days - A fresh HackMD release notes document has been pinned to the **#*release-xdotx** Slack channel
- [ ] T-minus 7 days - A draft for the announcement blog post has been started
- [ ] T-minus 7 days - An announcement has been made in the **#general** Slack channel that the cut of `pkg` is immminent
- [ ] T-minus 7 days - The nightly release build status has been verified for each of the core knative.dev repos
- [ ] knative.dev/hack
- [ ] knative.dev/pkg
- [ ] knative.dev/networking
- [ ] knative.dev/caching
- [ ] knative.dev/reconciler-test
- [ ] knative.dev/control-protocol
- [ ] T-minus 1 day - Obtained ACK from each WG leads that the release is imminent and is green-lighted
- [ ] T-minus 1 day - A re-check of the nightly release build status has been done for each of the core knative.dev repos
- [ ] knative.dev/serving
- [ ] knative.dev/net-certmanager
- [ ] knative.dev/net-contour
- [ ] knative.dev/net-http01
- [ ] knative.dev/net-istio
- [ ] knative.dev/net-kourier
- [ ] knative.dev/net-gateway-api
- [ ] knative.dev/eventing
- [ ] knative.dev/sample-controller
- [ ] knative.dev/eventing-ceph
- [ ] knative.dev/eventing-kogito
- [ ] knative.dev/eventing-rabbitmq
- [ ] knative.dev/sample-source
- [ ] knative.dev/client
- [ ] knative.dev/eventing-kafka
- [ ] knative.dev/eventing-redis
- [ ] knative.dev/eventing-github
- [ ] knative.dev/eventing-gitlab
- [ ] knative.dev/eventing-kafka-broker
- [ ] knative.dev/eventing-autoscaler-keda
- [ ] knative.dev/kn-plugin-admin
- [ ] knative.dev/kn-plugin-event
- [ ] knative.dev/kn-plugin-source-kafka
- [ ] knative.dev/kn-plugin-source-kamelet
- [ ] knative.dev/kn-plugin-quickstart
- [ ] knative.dev/docs
- [ ] Post release - Homebrew tap has been updated
- [ ] Post release - The client plugin's Homebrew repo has been updated
- [ ] Post release - Release schedule has been updated
- [ ] Post release - An announcement was made in the **#general** and **#operation** Slack channels that the new Knative release is out
- [ ] Post release - A blog post announcing the release has been published
