### ISSUE TITLE
[Release v1.8]: checklist

### ISSUE THREAD

**Issue by lionelvillard** [knative/release#164]
### Please change the title to include the current release version.

- [x] T-minus 30 days - Prior release leads have been removed from rotation (https://github.com/knative/community/pull/1163)
- [x] T-minus 30 days - New release leads have been added for the new rotation ((https://github.com/knative/community/pull/1163)
- [x] T-minus 30 days - A new Slack channel for the release has been created (using #release)
- [x] T-minus 30 days - Knobots update-deps job has been bumped to new release version (https://github.com/knative-sandbox/knobots/pull/230)
- [x] T-minus 14 days - The releasability defaults have been updated (https://github.com/knative-sandbox/knobots/pull/242)
- [x] T-minus 14 days - The releasability defaults update have been propagated thru all applicable `knative.dev` repos
- [x] T-minus 14 days - An announcement has been made in the **#general** Slack channel that `pkg` will be released in a week ([slack link](https://knative.slack.com/archives/C93E33SN8/p1664800096510739))
- [x] T-minus 7 days - A fresh HackMD release notes document has been pinned to the **#*release-xdotx** Slack channel - [hackmd](https://hackmd.io/cJwvzJ4eRVeqqiXzOPtxsA?edit)
- [ ] T-minus 7 days - A draft for the announcement blog post has been started
- [x] T-minus 7 days - An announcement has been made in the **#general** Slack channel that the cut of `pkg` is immminent - [slack](https://knative.slack.com/archives/C93E33SN8/p1665435748560189)
- [x] T-minus 7 days - The nightly release build status has been verified for each of the core knative.dev repos
- [x] knative.dev/hack
- [x] knative.dev/pkg
- [x] knative.dev/networking
- [x] knative.dev/caching
- [x] knative.dev/reconciler-test
- [x] knative.dev/control-protocol
- [x] T-minus 1 day - Obtained ACK from each WG leads that the release is imminent and is green-lighted
- [x] T-minus 1 day - A re-check of the nightly release build status has been done for each of the core knative.dev repos
- [x] knative.dev/serving
- [x] knative.dev/net-certmanager
- [x] knative.dev/net-contour
- [x] knative.dev/net-http01
- [x] knative.dev/net-istio
- [x] knative.dev/net-kourier
- [x] knative.dev/net-gateway-api
- [x] knative.dev/eventing
- [x] knative.dev/sample-controller
- [x] knative.dev/eventing-ceph
- [x] knative.dev/eventing-kogito
- [x] knative.dev/eventing-rabbitmq
- [x] knative.dev/sample-source
- [x] knative.dev/client - (optional) Check that [CHANGELOG.adoc](https://github.com/knative/client/blob/main/CHANGELOG.adoc) contains a section about the release, i.e. the top-level "(Unreleased)" section should be changed to point to the upcoming release version and number. It's not critical if the changelog is aligned after the release in retrospective. - If the validation fails, the fix should be trivial and could be either performed by the release leads or the client team.
- [x] knative.dev/eventing-kafka
- [x] knative.dev/eventing-redis
- [x] knative.dev/eventing-github
- [x] knative.dev/eventing-gitlab
- [x] knative.dev/eventing-kafka-broker
- [x] knative.dev/eventing-autoscaler-keda
- [x] knative.dev/kn-plugin-admin
- [x] knative.dev/kn-plugin-event
- [x] knative.dev/kn-plugin-source-kafka
- [x] knative.dev/kn-plugin-source-kamelet
- [x] knative.dev/kn-plugin-quickstart
- [x] knative.dev/kn-plugin-func
- [x] knative.dev/docs
- [x] Post release - Homebrew tap has been updated
- [x] Post release - The client plugin's Homebrew repo has been updated
- [x] Post release - Release schedule has been updated https://github.com/knative/release/pull/170
- [x] Post release - An announcement was made in the **#general** and **#operation** Slack channels that the new Knative release is out
- [x] Post release - A blog post announcing the release has been published

**Comment by dprotaso** [comment]
Can you update

https://github.com/knative/community/blob/main/mechanics/RELEASE-SCHEDULE.md

**Comment by nak3** [comment]
Sure. Sent the PR
- https://github.com/knative/release/pull/173
- https://github.com/knative/community/pull/1185
